village=input("마을의 이름은? ")
cost=input("비용추산은? ")
time=input("시간은 몇일? ")
person=input("사람은 몇명? ")

print("")
print("================================")
print("해당공사를 시작한", village, "에서는 대형공사가 시작되었다.")
print("해당공사의 규모는 대략", cost, "되는 공사다.")
print("기간은 대략", time, "일 정도된다.")
print("해당공사를 진행하는 인원은", person, "명이다.")
print("================================")